version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - public
    depends_on:
      - fc-node-app
    

  fc-node-app:
    build: .
    image: thiagopereira/fc-node-app
    networks:
      - public
    depends_on:
      - mysql


  mysql:
    image: mysql:5.7
    restart: always
    tty: true
    volumes: 
      - mysql_data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=fc-node-app
      - MYSQL_ROOT_PASSWORD=fc-node-app
    ports:
      - "3306:3306"
    networks:
      - public
    command: --innodb-use-native-aio=0

networks:
  public:
    driver: bridge


volumes:
  mysql_data: