# Comandos para a criação da imagem
FROM node:18-alpine
WORKDIR /app
COPY package.json .

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

RUN npm install --omit=dev
COPY . .

RUN npm install

ENV PORT=3000
EXPOSE $PORT

# Comandos que executam quando o container é criado
CMD [ "node", "index.js" ]