# Comandos para a criação da imagem
FROM node:18
WORKDIR /app

RUN apt-get update && \
    apt-get install wget -y

COPY package.json .

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN npm install
COPY . .

ENV PORT=3000
EXPOSE $PORT

# Comandos que executam quando o container é criado
CMD [ "node", "index.js" ]